// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteResult(name) {
    return $Call.ByID(3353369064, name);
}

/**
 * @param {$models.GUIRequest} request
 * @returns {$CancellablePromise<$models.GUIResult>}
 */
export function Execute(request) {
    return $Call.ByID(1364641005, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.GUISession} session
 * @returns {$CancellablePromise<string>}
 */
export function ExportCode(session) {
    return $Call.ByID(2201601457, session);
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<$models.GUISession>}
 */
export function ImportCode(code) {
    return $Call.ByID(1799329578, code).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GUIOptions>}
 */
export function GetOptions() {
    return $Call.ByID(3105337476).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GUISavedResult[]>}
 */
export function ListResults() {
    return $Call.ByID(2329432608).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.GUISession>}
 */
export function LoadResult(name) {
    return $Call.ByID(3330790871, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GUISession>}
 */
export function LoadSession() {
    return $Call.ByID(1005537618).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} name
 * @param {$models.GUISession} session
 * @returns {$CancellablePromise<void>}
 */
export function SaveResult(name, session) {
    return $Call.ByID(101267570, name, session);
}

/**
 * @param {$models.GUISession} session
 * @returns {$CancellablePromise<void>}
 */
export function SaveSession(session) {
    return $Call.ByID(2019746469, session);
}

// Private type creation functions
const $$createType0 = $models.GUIResult.createFrom;
const $$createType1 = $models.GUIOptions.createFrom;
const $$createType2 = $models.GUISavedResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.GUISession.createFrom;
