// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class GUIAffix {
    /**
     * Creates a new GUIAffix instance.
     * @param {Partial<GUIAffix>} [$$source = {}] - The source object to create the GUIAffix.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["level"] = 0;
        }
        if (!("wine" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["wine"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIAffix instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUIAffix}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GUIAffix(/** @type {Partial<GUIAffix>} */($$parsedSource));
    }
}

export class GUIAffixDetails {
    /**
     * Creates a new GUIAffixDetails instance.
     * @param {Partial<GUIAffixDetails>} [$$source = {}] - The source object to create the GUIAffixDetails.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("levels" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["levels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIAffixDetails instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUIAffixDetails}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("levels" in $$parsedSource) {
            $$parsedSource["levels"] = $$createField2_0($$parsedSource["levels"]);
        }
        return new GUIAffixDetails(/** @type {Partial<GUIAffixDetails>} */($$parsedSource));
    }
}

export class GUIOptions {
    /**
     * Creates a new GUIOptions instance.
     * @param {Partial<GUIOptions>} [$$source = {}] - The source object to create the GUIOptions.
     */
    constructor($$source = {}) {
        if (!("classes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["classes"] = [];
        }
        if (!("affixes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["affixes"] = [];
        }
        if (!("affixDetails" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: GUIAffixDetails }}
             */
            this["affixDetails"] = {};
        }
        if (!("rarities" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["rarities"] = [];
        }
        if (!("weaponModes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["weaponModes"] = [];
        }
        if (!("accessoryFilters" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["accessoryFilters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUIOptions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("classes" in $$parsedSource) {
            $$parsedSource["classes"] = $$createField0_0($$parsedSource["classes"]);
        }
        if ("affixes" in $$parsedSource) {
            $$parsedSource["affixes"] = $$createField1_0($$parsedSource["affixes"]);
        }
        if ("affixDetails" in $$parsedSource) {
            $$parsedSource["affixDetails"] = $$createField2_0($$parsedSource["affixDetails"]);
        }
        if ("rarities" in $$parsedSource) {
            $$parsedSource["rarities"] = $$createField3_0($$parsedSource["rarities"]);
        }
        if ("weaponModes" in $$parsedSource) {
            $$parsedSource["weaponModes"] = $$createField4_0($$parsedSource["weaponModes"]);
        }
        if ("accessoryFilters" in $$parsedSource) {
            $$parsedSource["accessoryFilters"] = $$createField5_0($$parsedSource["accessoryFilters"]);
        }
        return new GUIOptions(/** @type {Partial<GUIOptions>} */($$parsedSource));
    }
}

export class GUIPiece {
    /**
     * Creates a new GUIPiece instance.
     * @param {Partial<GUIPiece>} [$$source = {}] - The source object to create the GUIPiece.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("rarity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rarity"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("nativeAffixes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nativeAffixes"] = "";
        }
        if (!("gems" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gems"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIPiece instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUIPiece}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GUIPiece(/** @type {Partial<GUIPiece>} */($$parsedSource));
    }
}

export class GUIRequest {
    /**
     * Creates a new GUIRequest instance.
     * @param {Partial<GUIRequest>} [$$source = {}] - The source object to create the GUIRequest.
     */
    constructor($$source = {}) {
        if (!("characterClass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["characterClass"] = "";
        }
        if (!("weapon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["weapon"] = "";
        }
        if (!("minRarity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["minRarity"] = "";
        }
        if (!("maxRarity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["maxRarity"] = "";
        }
        if (!("ring" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ring"] = "";
        }
        if (!("amulet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["amulet"] = "";
        }
        if (!("affixes" in $$source)) {
            /**
             * @member
             * @type {GUIAffix[]}
             */
            this["affixes"] = [];
        }
        if (!("lowPerformance" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lowPerformance"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUIRequest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("affixes" in $$parsedSource) {
            $$parsedSource["affixes"] = $$createField6_0($$parsedSource["affixes"]);
        }
        return new GUIRequest(/** @type {Partial<GUIRequest>} */($$parsedSource));
    }
}

export class GUIResult {
    /**
     * Creates a new GUIResult instance.
     * @param {Partial<GUIResult>} [$$source = {}] - The source object to create the GUIResult.
     */
    constructor($$source = {}) {
        if (!("possible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["possible"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("sets" in $$source)) {
            /**
             * @member
             * @type {GUISet[]}
             */
            this["sets"] = [];
        }
        if (!("tested" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tested"] = 0;
        }
        if (!("seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUIResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sets" in $$parsedSource) {
            $$parsedSource["sets"] = $$createField2_0($$parsedSource["sets"]);
        }
        return new GUIResult(/** @type {Partial<GUIResult>} */($$parsedSource));
    }
}

export class GUISavedResult {
    /**
     * Creates a new GUISavedResult instance.
     * @param {Partial<GUISavedResult>} [$$source = {}] - The source object to create the GUISavedResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUISavedResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUISavedResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GUISavedResult(/** @type {Partial<GUISavedResult>} */($$parsedSource));
    }
}

export class GUISession {
    /**
     * Creates a new GUISession instance.
     * @param {Partial<GUISession>} [$$source = {}] - The source object to create the GUISession.
     */
    constructor($$source = {}) {
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {GUIRequest}
             */
            this["request"] = (new GUIRequest());
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {GUIResult}
             */
            this["result"] = (new GUIResult());
        }
        if (!("hasResult" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasResult"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUISession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUISession}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField0_0($$parsedSource["request"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new GUISession(/** @type {Partial<GUISession>} */($$parsedSource));
    }
}

export class GUISet {
    /**
     * Creates a new GUISet instance.
     * @param {Partial<GUISet>} [$$source = {}] - The source object to create the GUISet.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("price" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["price"] = "";
        }
        if (!("unusedGemSlots" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unusedGemSlots"] = 0;
        }
        if (!("unusedAffixSlots" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unusedAffixSlots"] = 0;
        }
        if (!("pieces" in $$source)) {
            /**
             * @member
             * @type {GUIPiece[]}
             */
            this["pieces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUISet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GUISet}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pieces" in $$parsedSource) {
            $$parsedSource["pieces"] = $$createField4_0($$parsedSource["pieces"]);
        }
        return new GUISet(/** @type {Partial<GUISet>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = GUIAffixDetails.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = GUIAffix.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = GUISet.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = GUIRequest.createFrom;
const $$createType9 = GUIResult.createFrom;
const $$createType10 = GUIPiece.createFrom;
const $$createType11 = $Create.Array($$createType10);
